// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCSA.WebAPI.FlightData.Data;

#nullable disable

namespace TCSA.WebAPI.FlightData.Data.Models
{
    [DbContext(typeof(FlightsDbContext))]
    [Migration("20250503185650_AiportModel")]
    partial class AiportModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AirportFlight", b =>
                {
                    b.Property<int>("DepartureAirportsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightsDepartingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartureAirportsId", "FlightsDepartingId");

                    b.HasIndex("FlightsDepartingId");

                    b.ToTable("AirportFlight");
                });

            modelBuilder.Entity("AirportFlight1", b =>
                {
                    b.Property<int>("ArrivalAirportsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightsArrivingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArrivalAirportsId", "FlightsArrivingId");

                    b.HasIndex("FlightsArrivingId");

                    b.ToTable("AirportFlight1");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightID")
                        .IsUnique();

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightID");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("AirportFlight", b =>
                {
                    b.HasOne("TCSA.WebAPI.FlightData.Models.Airport", null)
                        .WithMany()
                        .HasForeignKey("DepartureAirportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCSA.WebAPI.FlightData.Models.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightsDepartingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirportFlight1", b =>
                {
                    b.HasOne("TCSA.WebAPI.FlightData.Models.Airport", null)
                        .WithMany()
                        .HasForeignKey("ArrivalAirportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCSA.WebAPI.FlightData.Models.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightsArrivingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Airline", b =>
                {
                    b.HasOne("TCSA.WebAPI.FlightData.Models.Flight", "Flight")
                        .WithOne("Airline")
                        .HasForeignKey("TCSA.WebAPI.FlightData.Models.Airline", "FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Seat", b =>
                {
                    b.HasOne("TCSA.WebAPI.FlightData.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Flight", b =>
                {
                    b.Navigation("Airline");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
