// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCSA.WebAPI.FlightData.Data;

#nullable disable

namespace TCSA.WebAPI.FlightData.Data.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    [Migration("20250502194736_airlineModel")]
    partial class airlineModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightID")
                        .IsUnique();

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Airline", b =>
                {
                    b.HasOne("TCSA.WebAPI.FlightData.Models.Flight", "Flight")
                        .WithOne("Airline")
                        .HasForeignKey("TCSA.WebAPI.FlightData.Models.Airline", "FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("TCSA.WebAPI.FlightData.Models.Flight", b =>
                {
                    b.Navigation("Airline");
                });
#pragma warning restore 612, 618
        }
    }
}
